### ISSUE TITLE
Cannot provision webpart in wiki page

### ISSUE THREAD

**Issue by Djemel** [SubPointSolutions/spmeta2#451] opened 2015-04-21 08:54 UTC
Hi,

I am currently evaluating SPMeta2 doing a simple test:
- Create a calendar
- Create a wikipage
- Add a calendar webpart to th wikipage

I tried following code:
```
var teamCal = new ListDefinition()
                              {
                                  Title = "Team Calendar",
                                  TemplateType = BuiltInListTemplateTypeId.Events,
                                  Url = "Team Calendar"
                              };

var testPage = new WikiPageDefinition()
                               {
                                   Title = "Test Page",
                                   FileName = "test.aspx",
                                   Content = "Test wiki Page"
                               };
var teamCalWP = new WebPartDefinition()
                                {
                                    Title = "Team Cal",
                                    Id = "teamcal",
                                    WebpartXmlTemplate = BuiltInWebPartTemplates.ListViewWebPart,
                                    AddToPageContent = true,
                                    ZoneId = "Main",
                                    ZoneIndex = 0
                                };

var model =
                SPMeta2Model.NewWebModel(
                    web =>
                    web.AddList(teamCal)
                        .AddHostList(
                            BuiltInListDefinitions.SitePages,
                            list => list.AddWikiPage(testPage, page => page.AddWebPart(teamCalWP))));
return model;
```
unfortunately, I have the following error message
"One of the properties of the Web Part has an incorrect format. Microsoft SharePoint Foundation cannot deserialize the Web Part.  Check the format of the properties and try again."

Could you please help ?
Thank you

**Comment by SubPointSupport** [comment] 2015-04-21 09:19
Investigating, will keep you posted.

**Comment by SubPointSupport** [comment] 2015-04-21 09:33
Confirming that issue for both CSOM/SSOM implemetations.

**Comment by SubPointSupport** [comment] 2015-04-21 09:47
Solved.

There are two ways to solve that, here are the details:

##### 1) Use typed web part definition - ListViewWebPartDefinition

Pretty self-explaining, seems SharePoint does not like ListViewWebPart with missing bindings to the list.

```
var teamCal = new ListDefinition()
            {
                Title = "Team Calendar",
                TemplateType = BuiltInListTemplateTypeId.Events,
                Url = "Team Calendar"
            };

            var testPage = new WikiPageDefinition()
            {
                Title = "Test Page",
                FileName = "test.aspx",
                Content = "Test wiki Page"
            };

            // seems SharePoint does not like ListViewWebPart without bindings
            // let's use 'typed definition' for ListViewWebPartDefinition
            // var teamCalWP = new WebPartDefinition()

            var teamCalWP = new ListViewWebPartDefinition()
            {
                Title = "Team Cal",
                Id = "teamcal",
                AddToPageContent = true,
                ZoneId = "Main",
                ZoneIndex = 0,
                // setup binding, there are also ListId/ListUrl props
                ListTitle = teamCal.Title
            };

            // make sure the web part is provisioned AFTER teamCal list
            // we have binding by ListTitle to the list
            var model = SPMeta2Model.NewWebModel(web =>
            {
                web.AddList(teamCal);
                web.AddHostList(BuiltInListDefinitions.SitePages, list =>
                {
                    list.AddWikiPage(testPage, page =>
                    {
                        page.AddWebPart(teamCalWP);
                    });
                });
            });
```

##### 2) Use WebPartDefinition, but setup list bindings before provision
SPMeta2 does ListViewWebPart provision with pre-processing web part XML before actual provision. That works for CSOM, and we create same-same XML for the first provision for SSOM.

Here is an actual code from CSOM ListViewWebPartModelHandler, you can reuse this to form correct XML for your web part before proivision. wpXml would have correct XML with list binding, so that SharePoint would add the web part on a correct way.

Second provision for CSOM deletes the web part (CSOM limitation) and adds it again, SSOM would get the web part instance and try to update properties.
```
var wpXml = WebpartXmlExtensions.LoadWebpartXmlDocument(BuiltInWebPartTemplates.ListViewWebPart)
                                         .SetOrUpdateListVieweWebPartProperty("ListName", bindContext.ListId.ToString("B"))
                                         .SetOrUpdateListVieweWebPartProperty("ListId", bindContext.ListId.ToString("D").ToLower())
                                         .SetOrUpdateListVieweWebPartProperty("ViewGuid", bindContext.ViewId.ToString("D").ToLower())
                                         .SetTitleUrl(bindContext.TitleUrl)
                                         .ToString();
``

Hope that helps.

Also, check out the following sample for ListViewWebPart with binding to the calendar view:
http://docs.subpointsolutions.com/spmeta2/definitions/sharepoint-foundation/Webparts/ListViewWebPartDefinition/#Binding to calendar view

All the samples:
http://docs.subpointsolutions.com/spmeta2/scenarios/

And don't miss our Yammer Network:
https://www.yammer.com/spmeta2feedback

Cheers!

**Comment by SubPointSupport** [comment] 2015-04-22 02:54
@Djemel, would you please let us know how it goes, so that we close the ticket or perform the further investigation? Thanks!

**Comment by Djemel** [comment] 2015-04-22 05:44
Tested the first solution it works - thank you very much for the quick feedback.

Side question : any way to define the wikipage layout and then "target zone/table cell" when adding a webpart to a wikipage ?

**Comment by SubPointSupport** [comment] 2015-04-22 06:00
>>Tested the first solution it works - thank you very much for the quick feedback.
No worries, closing this one.

>>Side question : any way to define the wikipage layout and then "target zone/table cell" when adding a webpart to a wikipage ?
There is a way, has not been documented yet.
Created a ticket for that - https://github.com/SubPointSolutions/spmeta2-docs/issues/36

Next, here is what can you do and some background
A few useful links:
* https://github.com/SubPointSolutions/spmeta2/issues/48
* http://blog.mastykarz.nl/programmatically-adding-web-parts-rich-content-sharepoint-2010/
* http://passionatetechie.blogspot.com.au/2011/11/how-to-add-web-part-on-sharepoint-2010.html

Then, here are the steps:
1) Setup a wiki page layout with WikiPageDefinition.Content property - that would include these weird 'ms-rtestate-read ms-rte-wpbox' areas as per the mentioned posts 

2) Checkout our web part provision on wiki-publishing pages test here - https://github.com/SubPointSolutions/spmeta2/blob/master/SPMeta2/SPMeta2.Regression.Tests/Impl/Scenarios/WebpartScenariosTest.cs 

Check CanDeploy_WebpartToWikiPageContent() and CanDeploy_WebpartToPublishingPageContent() methods.

Essentially, we need to craft a special content areas for wiki/publishing pages, including the correct IDs and css classes (gosh, tell us more about that), and then make sure web part IDs match with these IDs inside content areas. Possible, but is not that easy to do.

Hope that would help and you would not spend much time on that.
Will update with the documentation and samples once they are ready.

Cheers!

**Closed by SubPointSupport** 2015-04-22 06:00 UTC
Labels: community feedback

**Comment by Djemel** [comment] 2015-04-22 06:31
Sweet ! Thank you :)

**Comment by benlime** [comment] 2016-11-23 12:12
I tried the same procedure as described by @SubPointSupport but actually I ran into an issue. When I'm using `ListViewWebpartDefinition` it's working properly but if I use the `XsltListViewWebPartDefinition` it's not working as expected. Maybe there is an issue? I need to use the `XsltListViewWebPartDefinition` because I must have the SP2013 look & feel.

**Comment by SubPointSupport** [comment] 2016-11-23 23:46
Alright, how does the model look like? Could you please open up a new issue (as we've got a template for them at github) and we'll start from there?

**Comment by benlime** [comment] 2016-11-25 10:12
Thanks for the quick reply. I'll open an issue in the next few days when I have access to the code again. :)

**Comment by SubPointSupport** [comment] 2016-11-27 09:27
Sweet, looking forward to replicate and solve that.
