### ISSUE TITLE
SPException "A duplicate field name "[fieldname]" was found"

### ISSUE THREAD

**Issue by bctw** [SubPointSolutions/spmeta2#705] opened 2015-10-21 16:33 UTC
When adding, for example, a Site Column to a Site model, if the Column already exists, I'm getting a SPMeta2.Exceptions.SPMeta2ModelDeploymentException (with inner exception: {"A duplicate field name \"fieldName\" was found."}).

Is this the expected behavior?  If so, that means I can't add items to the model that already exist -- that means it's hard/impossible to add additional things.

(For example, if I can't add a ListDefinition to a site model where the list already exists, then I can't add a new field to an *existing* list that I have already provisioned in the past.  Or am I missing something?)

**Comment by SubPointSupport** [comment] 2015-10-21 22:03
No, that is not an intended behavior.

Would you please share the field definition and the model, so that we can double-check it for you?

**Comment by SubPointSupport** [comment] 2015-10-22 22:01
Confirmed with the client, closing - https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=602843142

```
I determined that, at one point, two FieldDefinitions shared a duplicate Guid, causing a failed deployment which left the Web in an unexpected state. I believe this is responsible for the behavior I am seeing. Nevertheless, it would be good if M2 could fail more gracefully when such a field is encountered (or have an option to ignore such issues).
```

**Closed by SubPointSupport** 2015-10-22 22:01 UTC
Labels: community-feedback, m2-research
