### ISSUE TITLE
ContentType Hidden Property not propagated when changed afterwards

### ISSUE THREAD

**Issue by andreasblueher** [SubPointSolutions/spmeta2#1055] opened 2017-07-28 08:45 UTC
Hello,

### Brief description
Please provide short description covering two areas:
* When changing ContentTypeDefinition Hidden=true it should not only be change for SiteContentType, but also for ListContentType
* Hidden = true only changes for SiteContentType

### SharePoint API
Which version of SharePoint runtime do you use? 
* SSOM

### SPMeta2 API
1.2.130

I first thought I could be related to Incremental udpates, but after disabling them Hidden property still wasn't propagated to the list content type. When I deleted the whole site and redeployed with Hidden=true being there from the beginning it worked! Both site and list contenttype had Hidden=true

**Comment by SubPointSupport** [comment] 2017-08-01 22:58
This one could be by SharePoint design. We need to double check this one.

**Comment by andreasblueher** [comment] 2017-08-02 21:19
I wrote some SSOM code myself to see if it's by design and indead it is. Writing ssom code and modifying the site content type doesn't change the hidden property, even changing the name doesn't do anything on the list content type.

I somehow don't want to believe, that this is actually how Microsoft intends it to be, but nevertheless the following thought came to my head:
Why does SPMeta always have to follow Microsoft implementation, even though it might be stupid? Having one definition for deploying a content type to my site and adding this definition via contenttypelink to a list, why shouldn't SPMeta be smart enough to figure out, that changing anything at site level, should also be propagated to list level. I don't see why people wouldn't want that, since you would get a different result if you create a new environment and deploy your definitions there.

I'm not sure if I underestimate the amount of code needed to achieve such kind of behavior, but I think it would be a nice improvement to the current situation and we had this "list contenttype is different than site contenttype" already a few times now if I remember correctly.

**Comment by SubPointSupport** [comment] 2017-08-08 02:14
>Writing ssom code and modifying the site content type doesn't change the hidden property, even changing the name doesn't do anything on the list content type.

Because list-scoped content type is kind of "disconnected" from the site/web level one. Such properties are managed on the "ContentTypeLink" object which is a legit SharePoint object and that's how SharePoint works. It allows people override some properties at the list level keeping separation on "visual" level - Hidden/Title and so on specific to a list. Field sets, on the other hard, are still being promoted to the list.

> it would be a nice improvement to the current situation and we had this "list contenttype is different than site contenttype" already a few times now if I remember correctly.

It might not. Agree, we had several bugs reported where a list content type seemed to be completely disconnected from the site/web level one. Couldn't figure out the reason, couldn't fix that. Once in a blue moon they do that thing, yes.

> Why does SPMeta always have to follow Microsoft implementation...
Sometimes we do, already handling tons of API inconsistency, bugs and issue. In that particular case we wont' implement such behaviour. We simple can't go and update every single list conent type with Hidden property - we don't know if list owners (people) intentionally want to see/hide these content types at the list level. Hence, it might not be the case that one wants to push everything from the site/web level to the list. List-scope is unique for every situation. We simply don't have information to make the right decision here.

**Comment by SubPointSupport** [comment] 2017-08-28 12:03
Related to ContentType Field Required=false does not propagete to List Field #918

Both issues are not going to be fixed within SPMeta2 anytime soon. Seems to be out of the box SharePoint behaviour confirmed and researched by @andreasbluehe . We might get back later to this and implement some kind of post-processing but for the time being it is closed.

**Closed by SubPointSupport** 2017-08-28 12:03 UTC
Labels: bug, community-feedback
