### ISSUE TITLE
Can't provision list with NoListTemplate template type

### ISSUE THREAD

**Issue by maxx2097** [SubPointSolutions/spmeta2#944] opened 2017-02-04 15:32 UTC
I have a problem provisioning (SSOM) a custom list without the Title field:

If I use BuiltInListTemplateTypeId.GenericList the Title field is added. 
Using BuiltInListTemplateTypeId.NoListTemplate throws an error upon Model validation.

Is this a bug or do I have to use some other concept?

Thanks!

Maxx

**Comment by SubPointSupport** [comment] 2017-02-05 02:23
Hey @maxx2097 , thanks for reporting this. It's bug, issue on our side. Here how it works.

SPMeta2 gas built-in definition validation to ensure that only well-formed data is provisioned. With ListDefinition, we require either TemplateType or TemplateName to be set. TemplateType is of "int" type, so that SPMeta2 checks if it's more than 0 and/or TemplateName is non-null an non-empty string.

Didn't expect  BuiltInListTemplateTypeId.NoListTemplate to be "0" and to be allowed value.

Fixinf that up, meanwhile you can "disable" validation on your side so that M2 won't check definitions.
provisionservice.PreDeploymentServices collection has bunch of service of type "PreDeploymentValidationServiceBase". You either can remove all of them or just call provisionservice.PreDeploymentServices.Clear() to get it up and running.

We are getting a solution here, adding test to ensure that the model with  BuiltInListTemplateTypeId.NoListTemplate value can be deployed.

Thanks again for reporting this, and btw, we've got a Yammer Network just in case you weren't across that: https://www.yammer.com/spmeta2feedback

Let us know how it works for you.

**Comment by SubPointSupport** [comment] 2017-02-05 03:15
@maxx2097, we double-checked what's going on there.

First of all, we can disable validation and put a few fixes across to allow BuiltInListTemplateTypeId.NoListTemplate passed to the provision. However, SharePoint always throws an exception with such list template as following:
```
{"Invalid list template."}
```
Both CSOM/SSOM don't allow list provision with TemplateType set to "0" (which is BuiltInListTemplateTypeId.NoListTemplate). 

Seems to be by design SharePoint behavious, so we are reverting our fixes. Not sure if a list without title column can be created by these means, but if there is a way - let us know, will incorporate that into SPMeta2 library and put some testing around. Closing this ticket but feel free to comment and put more details as needed.

**Closed by SubPointSupport** 2017-02-05 03:15 UTC
Labels: bug, community-feedback

**Comment by maxx2097** [comment] 2017-02-07 21:24
Thanks for your feedback!

BTW... I cant join your Yammer space... I can only request to access it, but I never get an email (also checked spam folder), etc.

**Comment by SubPointSupport** [comment] 2017-02-07 21:38
Sure, no worries. Already approved.
