### ISSUE TITLE
.AddWorkflowAssociation() should support list scoped content types

### ISSUE THREAD

**Issue by adaoust** [SubPointSolutions/spmeta2#980] opened 2017-03-16 16:38 UTC
Hi @SubPointSupport,

**Issue:**

For a list content type (`ContentTypeLinkModelNode`), the CSOM `WorkflowAssociationModelHandler` is unable to perform the update on the content type object at the end of the `DeployContentTypeWorkflowAssociationDefinition()` method.

It either throws the exception
-> `"The content type has no children."` when doing `contentType.Update(true)` for both a new association and an existing one.
or
-> `"The object has been updated by another user since it was last fetched."` when doing `contentType.Update(false)` for a new association.

**Resolution:**

Not doing the update at all for a new association seems to work perfectly fine and doing the `contentType.Update(false)` works when updating an existing association.

**Also, FYI:** 

It took me some time to realize that the `WorkflowAssociationModelHandler` lets us associate workflows to content types, because the Syntax `.AddWorkflowAssociation()` is missing for the `ContentTypeLinkModelNode` (it does not implement `IWorkflowAssociationHostModelNode`).

Thanks,

Alex

**Comment by SubPointSupport** [comment] 2017-03-16 22:02
Hey @adaoust, that's by design, but we definitely can improve that bit. The thing is that  "list scoped content types" aren't really "available" much with SPMeta2. The fact that workflow association works on ContentTypeLinkModelNode is nearly a pure luck, we wonder why it does not throw exception, and for sure that has never been tested.

Nevertheless, here is what we can do:
* Enhance syntax - .AddWorkflowAssociation() on ContentTypeLinkModelNode
* Add regression tests on workflow association on a list content type (both CSOM/SSOM)

Would it solve your particular case?

**Comment by adaoust** [comment] 2017-03-17 13:49
That would definitely be great!

However, like I mentioned, the current implementation of the handler throws an exception at `contentType.Update(true)`, I feel like it would have to be revised so that when the content type is list scoped, it does the update differently (or not at all - because it seems to work without it).

Thanks,

Alex

**Comment by SubPointSupport** [comment] 2017-03-19 22:07
Sweet, will do. 

Current implementation was never designed to work with list scoped fields. The assumption and the syntax was only available under site/web content types so that .Update(true) was always a case. Pretty much, anything what is not exposed via .AddXXX() syntax was never designed neither tested to work.

We are looking into that one improving and covering with regression tests to make it work for both CSOM/SSOM. Will be included in 1.2.120 release very soon.

**Closed** 2017-03-20 14:37 UTC
Labels: community-feedback, enhancement

**Comment by SubPointSupport** [comment] 2017-03-20 15:14
Done, 1.2.120-beta4 is out. cc @adaoust

**Comment by bradgarner** [comment] 2017-04-04 19:31
Hey guys! Don't mean to bring up old issues but I wanted to let you know that I verified that the AddWorkflowAssociation() on ContentTypeLinkModelNode works very well but I have issues when the content type is read-only due to the use of the Content Type Hub.

What is strange about this is that the association does happen and appears to be setup properly but there is an error thrown when deploying the model that states that the content type is read-only.

**Comment by SubPointSupport** [comment] 2017-04-04 22:59
Hey @bradgarner, thanks for sharing this.

Indeed, that's a pure luck that workflow gets attached under a hub-pushed content type due to ReadOnly flag. Frankly saying, we aren't sure how it might work.

First of all, updating such a content type might result in "deattaching" it from the content type hub. Meaning that the further updates from the content type hub won't be propagated down to that updated, changed content type.

Secondly, we don't call .Update() method on a list content type in this particular case. We'll have a deeper look trying to figure out where exactly exception occurs. 

As a workaround, we might run somethinng like this:
```cs
if(contentType.ReadOnly) {
 try {
  // attach workflow
} catch(Exception expectedException)
 // do nothing as we expect it to wreck :)
} 
```

However, would you please share stacktrace, exception and more details if possible? Keen to narrow down the issue so that we'll be able to fix it faster.

**Comment by SubPointSupport** [comment] 2017-04-04 23:00
We'd also suggest opening up a new issue, would you please? We'll continue investigation on a new one referring to this one.
