### ISSUE TITLE
WebNavigationSettingsDefinition - missed impl for AddNewPagesToNavigation/CreateFriendlyUrlsForNewPages props

### ISSUE THREAD

**Issue by ashuetawah** [SubPointSolutions/spmeta2#906] opened 2016-10-12 06:09 UTC
I am trying to update default page settings in a publishing web with below code, which seems not working as expected.

```cs
var site = SPMeta2Model.NewSiteModel();
var rootWeb = SPMeta2Model.NewWebModel();

rootWeb.AddWebNavigationSettings(new WebNavigationSettingsDefinition { 
 AddNewPagesToNavigation = false, 
 CreateFriendlyUrlsForNewPages = false });

csom.DeploySiteModel(clientContext, site);
csom.DeployWebModel(clientContext, rootWeb);
```

Initial research:
AddNewPagesToNavigation / CreateFriendlyUrlsForNewPages present in WebNavigationSettingsDefinition but never ever used within provision.

Further investigation, implementation for CSOM/SSOM, regression testing with [ExpectValidation] attributes is a must.

**Comment by SubPointSupport** [comment] 2016-10-12 09:12
Hm. Frankly saying, this is bug.

We made an investigation and found that neither AddNewPagesToNavigation nor CreateFriendlyUrlsForNewPages properties are used. They were never used within SPMeta2 library, and were never testing in any tests or regression. 

Most likely, initial implementation was pushed as part of the customer's feedback and these props were  left for "TOTO later".

We'll ivestigate and implement these both props this week. Clearly, miss from our side.

**Comment by SubPointSupport** [comment] 2016-10-12 09:14
AddNewPagesToNavigation / CreateFriendlyUrlsForNewPages present in WebNavigationSettingsDefinition but never ever used within provision.

Further investigation, implementation for CSOM/SSOM, regression testing with [ExpectValidation] attributes is a must.

**Comment by andreasblueher** [comment] 2016-10-12 10:57
I would like to implement this if it hasn't been started already by someone else.

**Comment by SubPointSupport** [comment] 2016-10-12 11:00
No, it hasn't been. 

We aren't sure that are these props yet. Meaning to which SP-props they should be mapped.
Have a look, once implemented we'll help out with the regression testing. Thinking to write up some documentation on regression testing. You need one?

**Comment by andreasblueher** [comment] 2016-10-12 11:03
Yeah that would definitely be helpful. I think I remember talking about this already in chat with Anton, but to be honest it has been a long time since.

**Comment by SubPointSupport** [comment] 2016-10-12 11:04
Taken by @andreasblueher 

These are officially in the current sprint:
Add documentation on contribution flow #912
Add documentation on regression testing #911

**Comment by SubPointSupport** [comment] 2016-10-12 11:10
Model handles, both CSOM/SSOM, should be fine. You worked with them early, as we remember.

We'll have a guide on the regression tomorrow so that you'll be able to work with regression attributes, write and run regression tests.

**Comment by ashuetawah** [comment] 2016-10-12 11:35
There are CSOM properties, which I have written now to work around.
currentSettings = new WebNavigationSettings(clientContext, clientContext.Web);
                currentSettings.AddNewPagesToNavigation = false;
                currentSettings.CreateFriendlyUrlsForNewPages = false;
This is present in Microsoft.SharePoint.Client.Publishing.Navigation.

**Comment by andreasblueher** [comment] 2016-10-12 12:27
I can't find a WebNavigationSettingsDefinitionValidator class. Does [ExpectValidation] relate to regression tests or to validation? Looking forward to regression documentation.

**Comment by SubPointSupport** [comment] 2016-10-12 23:41
Tests -> Validators -> SPMeta2.Regression.CSOM.Standard -> Validation -> WebNavigationSettingsDefinitionValidator

Validation handlers are split up by CSOM/SSON and by foundation and standard. Same as provision handlers.

Some CSOM validators has "Client" prefix in the name to avoid messing up VS autocomplete.

**Comment by SubPointSupport** [comment] 2016-10-14 08:01
@andreasblueher , we've got draft on the regression testing here:
https://github.com/SubPointSolutions/spmeta2/blob/1.2.95-beta2/SPMeta2/SubPointSolutions.Docs/Views/SPMeta2/extensibility/regression-testing.md

having some issues with publishing it to the docs-dev, sorting out. Have a look, let us know how the draft looks like. Will fix up and push it as fast as we can.

**Comment by SubPointSupport** [comment] 2016-10-16 23:51
@andreasblueher how did you go? 

We'll be closing sprint today moving this one to the next sprint. Not sure what the state is so that double-checking it.

**Comment by andreasblueher** [comment] 2016-10-17 06:34
@SubPointSupport I haven't been in the office since Thursday and didn't have the chance to look at your draft.

Most of this has been implemented from my point of view, but I couldn't really test it nor am I sure if the code for regression is correct at all. I could create a pull request and you could look into it, if you're up for that.

**Comment by SubPointSupport** [comment] 2016-10-17 06:38
Sweet! Go for the pull request,  that would be wonderful. 
Will have a look and either finish off to include in current beta or leave as it is.

**Comment by SubPointSupport** [comment] 2016-10-17 10:50
Merged pull request. Running tests and fixing up all outstanding stuff.
Please avoid working on this one, we'll push today/tomorrow in in beta2.

**Comment by andreasblueher** [comment] 2016-10-17 12:29
@SubPointSupport I started reading your documentation on Regression testing, but it's a lot to process and I'll need to read it a few more times while checking the code when I got some more time.

**Comment by SubPointSupport** [comment] 2016-10-17 22:35
Sure, we'll put more code and screens as we go. Thanks!

**Closed** 2016-10-24 08:16 UTC
Labels: bug, community-feedback, community-pr, contribution-easy, taken-by-community
