### ISSUE TITLE
Provisiong Views in a Page doesn't update

### ISSUE THREAD

**Issue by lllpsi** [SubPointSolutions/spmeta2#814] opened 2016-03-18 13:36 UTC
Using latest SPMeta2 and SP 2010,

When a list/document library view was updated, any existing pages that references the view doesn't get updated.

For example: 
List Old View 
"Title","Name"
List New View
"Title","Name","Blah"

Reprovisioning page doesn't show the newly updated view.

Workaround: Delete page and reprovision.

**Comment by SubPointSupport** [comment] 2016-03-20 01:16
That's an expected result, default SharePoint behaviour. 

All web part that refer to a list view have a shadow copy of the view behind the scenes. That means that every single web part has a "local copy" of the target view and that's the default SharePoint behaviour. 

All updates to the view won't change the views which are related to the web part. As a workaround, a deletion of the page and re-provisioning can be recommended, or re-provisioning of the target web part can be recommended as well.

SharePoint's "by design" feature, won't be fixed within M2.

**Closed by SubPointSupport** 2016-03-20 01:16 UTC
Labels: wontfix
