### ISSUE TITLE
Implement change of fieldtype, other model modifications as requirements evolve

### ISSUE THREAD

**Issue by bctw** [SubPointSolutions/spmeta2#720] opened 2015-10-27 00:55 UTC
Consider the following scenario:

A FieldDefinition is created of BuiltInFieldType.Text.  The field definition is added to a model and deployed.

Now, a requirement exists to change the FieldType to a multi-line (Note) field.

Changing the SPMeta2 definition schema Poco to "Note" Fieldtype and re-deploying does not work.

(This can be done using the CSOM by changing the SchemaXml property of the Field object).

In real-world scenarios, certain field types are likely to change and "grow" over time, due to changing requirements.  It would be good if:

a) SPMeta2 supported these for non-destructive changes (e.g. Text => Note)
b) SPMeta2 support all available types of changes -- including destructive changes -- that the Csom/Ssom can do.  e.g. Note => text field might result in data truncation assuming the call to the Csom would allow it to occur.

Ideally by specifying a "AllowDestructiveModifications" flag and a parameter that would be a collection containing objects that it's okay to destructively modify.  (e.g. a collection that contained various SPMeta2 Definition objects, e.g. FieldDefinition or ContentTypeDefinition, etc.).

**Comment by SubPointSupport** [comment] 2015-10-27 23:08
Correct, current implementation does not change the field type. All makes sense, would be a good feature of M2.

Both non-destructive and destructive updates can be implemented, as well as covered by the regression testing. To get started, it would be nice to have a matrix with the possible field type changes.

**Comment by bctw** [comment] 2015-10-28 01:07
Sure, I will put together a matrix of field types.  

Related question: what about essentially non-destructive changes like:

* changing the Display name of a field.
* changing a field to be Required

These changes are also not processed for existing items, right?  It would be good if these (non-destructive changes) were processed too.  Broadly speaking, they are all field property changes.

**Comment by SubPointSupport** [comment] 2015-10-28 02:25
Would be nice to have, so that we'll push test and start working on it.

As for the updates, a bit incorrect. Here is the general flow:
* create if artifacts does not exists
* update if artifact exists

The updated props are limited to:
*  common sense (Field.ID won'be changed or ContentType.Name)
* API limitations (not everything is available in CSOM)
* potential data corruptions (no deletes ever, or Field.Type kinda risky to change)
* M2 gaps (have not been implemented yet)

The goal is to have predictable and repeatable outcome after first provision and further provisions over.

**Comment by bctw** [comment] 2015-10-28 14:29
Right, everything has to be predictable.  That's why I would propose that the Csom/SsomProvisionerService have updateflag options that you would configure.

I would suggest using a bitmask so you would specify like:

// default -- no updates to existing artifacts
csomService.AllowUpdates = ProvisioningUpdates.None

//allow non-destructive changes like DisplayName, Required, etc.
csomService.AllowUpdates = ProvisioningUpdates.NonDestructive

// allow non-destructive changes & destructive changes like changing fieldTypes
csomService.AllowUpdates = ProvisioningUpdates.NonDestructive | ProvisioningUpdates.Destructive

This requires familiarity with an implementation of bitwise operators, e.g. https://www.safaribooksonline.com/library/view/c-cookbook/0596003390/ch04s05.html

**Comment by bctw** [comment] 2015-10-28 14:32
The following types of columns should be changeable to other items in the set:
Text, Note, Choice, Number, Currency, DateTime

Restrictions: It should not be possible to change the type of the "Title" column (since this is inheriting from the Item contentType).

Properties that should be changeable:
DisplayName, Required, EnforceUniqueValues, DefaultValue, Choices (for choice columns)

![interchangeable column types](https://cloud.githubusercontent.com/assets/14811246/10791440/d8e9d45a-7d5e-11e5-83f9-abc7a61c9de1.PNG)

**Comment by rolandoldengarm** [comment] 2016-11-15 19:41
This is quite important to us... Any ETA on this?

**Comment by SubPointSupport** [comment] 2016-11-20 21:51
Won't be implemented any soon. We may have more visibility in December/January. Right now there are no plans to implement this one.

**Comment by SubPointSupport** [comment] 2017-04-12 00:22
Closing due to lack of popularity, moving to Nice-To-Have.

**Closed by SubPointSupport** 2017-04-12 00:22 UTC
Labels: community-feedback, enhancement
