### ISSUE TITLE
ContentType Field Required=false  does not propagete to List Field

### ISSUE THREAD

**Issue by milleraa** [SubPointSolutions/spmeta2#918] opened 2016-10-18 03:40 UTC
Hello.

I've met the issue while making content type field not required.

Explanation is in the code comments.

SSOM

```
Major  Minor  Build  Revision
-----  -----  -----  --------
15     0      4841   1000
```

```
            var siteModel = SPMeta2Model
                          .NewSiteModel(site =>
                          {
                              site
                                   .AddField(SiteColumns.Quantity)
                                   .AddContentType(ContentTypes.TestItemContentType, ct =>
                                  {
                                      ct
                                           .AddContentTypeFieldLink(SiteColumns.Quantity);// this is required site column
                                  });
                          });

            var webModel = SPMeta2Model
                            .NewWebModel(web =>
                            {
                                web
                                    .AddList(Lists.TestItems, list =>
                                    {
                                        list
                                            .AddHideContentTypeLinks(new HideContentTypeLinksDefinition
                                            {
                                                ContentTypes = { new ContentTypeLinkValue { ContentTypeName = "Item" }, new ContentTypeLinkValue() { ContentTypeName = "Элемент" } }
                                            })
                                            .AddContentTypeLink(ContentTypes.TestItemContentType)
                                            .AddListView(new ListViewDefinition {
                                                Url = "AllItems.aspx",
                                                Title = "Все элементы",
                                                Fields = {
                                                    BuiltInFieldDefinitions.LinkTitle.InternalName,
                                                    SiteColumns.Quantity.InternalName
                                                }
                                            });
                                    });
                            });

            var siteModelV2 = SPMeta2Model
                          .NewSiteModel(site =>
                          {
                              site
                                   .AddContentType(ContentTypes.TestItemContentType, ct =>
                                   {
                                       ct
                                            .AddContentTypeFieldLink(new ContentTypeFieldLinkDefinition
                                            {
                                                FieldId = SiteColumns.Quantity.Id,
                                                Required = false,
                                            });
                                   });
                          });

            var webModelV2 = SPMeta2Model
                           .NewWebModel(web =>
                           {
                               web
                                   .AddList(Lists.TestItems, list =>
                                   {
                                       list
                                           .AddContentTypeLink(ContentTypes.TestItemContentType);
                                   });
                           });


            var service = new SSOMProvisionService();

            // 1st run. Field is required in ContentType. Required field validatior works on item form but not works on DataSheetView

            using (var site = new SPSite(url))
            {
                service.DeploySiteModel(site, siteModel);
            }

            using (var site = new SPSite(url))
            using (var web = site.OpenWeb())
            {
                service.DeployWebModel(web, webModel);
            }

            // 2nd run of same model, Field is required in ContentType. Required field validatior works on item form and WORKS on DataSheetView

            using (var site = new SPSite(url))
            {
                service.DeploySiteModel(site, siteModel);
            }

            using (var site = new SPSite(url))
            using (var web = site.OpenWeb())
            {
                service.DeployWebModel(web, webModel);
            }

            Console.ReadLine();

            // Run updated model to make field not required in content type. 
            // On item form field has not * sign but required field validator works, in datasheetview required fields validator works too.
            // In content type on site level and list level Field is not required, but in list fields it is required
            using (var site = new SPSite(url))
            {
                service.DeploySiteModel(site, siteModelV2);
            }

            using (var site = new SPSite(url))
            using (var web = site.OpenWeb())
            {
                service.DeployWebModel(web, webModelV2);
            }
```

**Comment by SubPointSupport** [comment] 2017-08-28 12:03
Related to ContentType Hidden Property not propagated when changed afterwards #1055


Both issues are not going to be fixed within SPMeta2 anytime soon. Seems to be out of the box SharePoint behaviour confirmed and researched by @andreasbluehe . We might get back later to this and implement some kind of post-processing but for the time being it is closed.

**Closed by SubPointSupport** 2017-08-28 12:03 UTC
Labels: bug, community-feedback
