### ISSUE TITLE
ListViewDefinition Scope hides "Folders" in View settings

### ISSUE THREAD

**Issue by leolorenzoluis** [SubPointSolutions/spmeta2#796] opened 2016-02-26 02:16 UTC
Using latest version of M2 and SharePoint 2010, if I set the ListViewDefinition Scope to RecursiveAll then it hides the Folder property and it doesn't show "Show in All".

**Comment by sebastianmattar** [comment] 2016-03-01 20:50
This seems to be a normal SharePoint behaviour. 
As you can't set "RecursiveAll" via the GUI (to my knowledge) i tried the following: I manually created a view and set the Scope to RecursiveAll using PowerShell. This made the "Folder" options disappear from the ViewEdit.aspx page.
My environment is SP2013 but this probably works the same way in SP2010.

**Comment by SubPointSupport** [comment] 2016-03-02 08:44
Confirming that with current dev branch, CanDeploy_XsltListViewWebPart_As_GridView test run on SP2013 and SSOM fails.

In the target list view we have Folder property hidden, and it doesn't show "Show in All" - excactly as described in the tickets.

Checking, thanks for reporting this.

**Comment by SubPointSupport** [comment] 2016-03-02 21:41
Seems to be an issue with the list view provision under SSOM. CSOM works well, and SSOM gives issues while provisioning list view in the "Grid" mode under SP2013 SP1. 

Regression, investigating the cause. Could be toggling some props on the list view.

**Comment by SubPointSupport** [comment] 2016-03-06 10:07
Fixed the test, but it was not related to the original issues of the ticket,

Frankly saying, not too sure what's wrong and how it can be replicated. SP2013 does not have that option on OOTB lists and libraries, the views don't have that option. 

@leolorenzoluis, would you please share the model and then the list / view settings on which there is such option and on which there is no such option?

**Comment by SubPointSupport** [comment] 2016-03-12 03:40
Closing until it can be replicated with concrete model / environment.

**Closed by SubPointSupport** 2016-03-12 03:40 UTC
Labels: bug, community-feedback, sp2010-standard
