### ISSUE TITLE
Empty Composed Looks when uploading Sandbox Solution

### ISSUE THREAD

**Issue by esuhendra** [SubPointSolutions/spmeta2#970] opened 2017-03-01 04:14 UTC
Hi guys,
Found an issue with uploading sandbox solutions. 
It looks like whenever I upload a sandbox solution (declarative XML), it deletes ALL entries from the Composed Looks list.

I am using SPMeta2 v1.2.80 CSOM.

Diagnostic info:
```
SPMeta2.Diagnostic.DiagnosticInfo SPMeta2FileVersion:[1.2.17057.1048] SPMeta2FileLocation:[E:\Development\Trunk\SharePointOnline\NET.SPProvisionTool\NET.SPProvisionForm\bin\Debug\SPMeta2.dll] CSOMFileVersion:[16.1.3912.1204] CSOMFileLocation:[E:\Development\Trunk\SharePointOnline\NET.SPProvisionTool\Bluebox.NET.SPProvisionForm\bin\Debug\Microsoft.SharePoint.Client.dll] Convert(p.IsSSOMDetected):[False]
```

The Sandbox definition:
```
 model.AddSandboxSolutions(element.Elements("Solution").Select(e =>
                    new SandboxSolutionDefinition
                    {
                        FileName = e.Attribute(BuiltInFieldAttributes.Name).Value,
                        Content = System.IO.File.ReadAllBytes(e.Attribute("Path").Value),
                        SolutionId = new Guid(e.Attribute(BuiltInFieldAttributes.ID).Value),
                        Activate = true
                    }
                ));
```
It works fine if I upload the Sandbox solution manually.

**Comment by SubPointSupport** [comment] 2017-03-01 04:19
Sandbox provision for CSOM uses design package provision API. We'll check what's going on there but it could be SharePoint's by design behavior. As sandbox solution provision isn't exposed via CSOM, we and other folks use design package API to push sandbox file to SharePoint. Hence, that's why it may have some side effects such as Composed Looks list clean up.

**Comment by SubPointSupport** [comment] 2017-04-24 03:58
@esuhendra seems to be out of the box SharePoint's behavior.

With CSOM, we use design package API to deploy sandbox solution. It works differently to the web UI experience while deploying sandbox solution manually. With reflector, the following code can be seen while solution package is being deployed:

Microsoft.SharePoint.Publishing.DesignPackage -> internal static void Install(SPSite site, DesignPackageInfo info, Stream data)


```cs

if (!site.IsSmallBusinessWebsite())
	{
		DesignPackage.DeleteNonDefaultMobileChannels(rootWeb, info);
		DesignPackage.DeleteDesignGalleryListItems(rootWeb, info);
	}
```
That one seems to be the very issue you reported. Unfortionatly, we can't see any workaround here apart activating IsSmallBusinessWebsite feature with ID  "SmallBusinessWebsite	48c33d5d-acff-4400-a684-351c2beda865". Closing this one we nothing much we can do. Let us know if there is a better way to handle sucg situation with CSOM.

**Closed by SubPointSupport** 2017-04-24 03:58 UTC
Labels: bug, community-feedback

**Comment by esuhendra** [comment] 2017-05-02 23:53
Yeah I had a feeling that it's up to CSOM code. At least for my case it's for provisioning new site, so I can just add those default composed looks.
Thanks for looking into this!

**Comment by SubPointSupport** [comment] 2017-05-03 01:01
Yea, CSOM has its limitations, pity to give up here.
