### ISSUE TITLE
SharePoint List Title appears as GUID when not explicitly set

### ISSUE THREAD

**Issue by maerger** [SubPointSolutions/spmeta2#759] opened 2016-02-02 08:32 UTC
Hi there,

When I provision a site model including a custom List on a site collection with base language German (1031) the List titles appears as a GUID in any language than Englisch (1033). I have to explicitely set the Title Resource for each language to fix this:

e.g.
listDef.TitleResource.Add(new ValueForUICulture { CultureId = 1031, Value = "List1" });            

If the site collection base language is Englisch (1031) the tiles for all languages are the same also without setting the title resources.

Bug or feature? ;-)

Best 
Roman

**Comment by SubPointSupport** [comment] 2016-02-02 08:35
Hard to say from the first sign. Will have to play around and see what's there.
Thanks for reporting that, @maerger

**Comment by SubPointSupport** [comment] 2016-02-02 08:39
Would you mind to share some models / definitions you have?
Also, SP2013 / O365?

**Comment by maerger** [comment] 2016-02-02 13:04
> Would you mind to share some models / definitions you have?
This is the code I use to define a List:
`            var listDef = new ListDefinition
            {
                ContentTypesEnabled = true,
                Title = Title,
                Description = description,
                TemplateType = BuiltInListTemplateTypeId.GenericList,
                CustomUrl = string.Format("Lists/{0}", listUrl)
            };
            rootWebModel.AddList(listDef, list =>
                AddDefaultContentType(list, masterDataContentTypes, contentTypeName));
            lists.Add(listDef);`
SP 2013 on-prem

**Comment by sebastianmattar** [comment] 2016-02-25 06:41
I can reproduce the behaviour with SP2010 SSOM. If you want to I can try to take care of this.

**Comment by sebastianmattar** [comment] 2016-02-25 08:20
After some research with SP2013 SSOM I found the following explanation:
- The Title property behaves differently depending on the current UI locale and the default language of the SPWeb
- creating a list, an internal "NewListTitle" property is set as well as TitleResources for all languages that are installed in the SPWeb
- When updating a list Title, the TitleResource of the the current UI locale is updated. If the current UI locale equals the default language of the SPWeb, the list "NewListTitle" property is updated as well.
- If the current UI locale equals the default locale of the Web, the "NewListTitle" property is returned. Otherwise a TitleResource is used.
- As the provisioning usually runs in locale 1033, setting the Title property will only update the TitleResource for locale 1033 but not the "NewListTitle" property
- Checking the disassembled code the only way to update the "NewListTitle" property is to temporarily set the Thread UI to the default language of the Web

What do you think?

**Comment by SubPointSupport** [comment] 2016-02-25 21:29
This is awesome, nice stuff, @sebastianmattar 

Is that only SP2010 related issue, or can be reproduced with SP2013?
We had other report of this issue on SP2010, but could not reproduce it yet.

Going to give it another try.

**Comment by sebastianmattar** [comment] 2016-02-25 22:17
I can reproduce it with SP2013 (SSOM) and SP2010 using the German language pack.

**Comment by max-cyberia** [comment] 2016-02-26 02:26
Hi,
I can reproduce the behaviour with SPS2010 SSOM, Russian Language pack.
My research has shown that Title in SchemaXml is Guid, but Title in SchemaXmlInCurrentUICulture is correct.
Fix it - set TitleResource in ListDefinition Title is correct.

**Comment by sebastianmattar** [comment] 2016-02-26 07:22
The Description field also has this behavior. Have a look at this pseudocode of the property in the SPList class:
```
public string Description
{
	get
	{
		if (System.Globalization.CultureInfo.CurrentUICulture.LCID != this.Lists.Web.UICulture.LCID)
		{
			return this.DescriptionResource.Value;
		}
		if (obj != null)
		{
			return (string)this.m_ListAttributesDict["Description"];
		}
	}
    set
	{
		if (!Microsoft.SharePoint.Utilities.SPUtility.StsCompareStrings(this.Description, value))
		{
			this.DescriptionResource.Value = value;
		}
		if (System.Globalization.CultureInfo.CurrentUICulture.LCID == this.Lists.Web.UICulture.LCID)
		{
			this.m_ListAttributesDict["Description"] = value;
		}
	}
}
```

**Comment by sebastianmattar** [comment] 2016-02-26 23:28
I found the same behavior with SPWeb (Title/Description field can't be updated)

**Comment by SubPointSupport** [comment] 2017-04-04 11:58
Closing. Will reopen once fix is needed.

**Closed by SubPointSupport** 2017-04-04 11:58 UTC
Labels: bug, community-feedback, m2-research
